app = "hummeraudio"
primary_region = "iad"

[build]

[env]
  PORT = "8080"
  HUMMER_TORCH_THREADS = "1"
  OMP_NUM_THREADS = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "90s"
    method = "get"
    path = "/api/health"
    protocol = "http"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1
